version: '3.2'

services:
  letsencrypt:
    image: letsencrypt:latest
    build: .
    environment:
      - FQDN
      - BOTO_CONFIG=/app/.boto
    volumes:
      - ~/.config:/root/.config
      - ~/.kube:/root/.kube
